### ISSUE TITLE
Can't find variable: Client

### ISSUE THREAD

**Issue by jveldboom** [innFactory/react-native-aws-mobile-analytics#1]
I've been seeing the above error within the Google Play Console and believe the issue is caused by a reference error on [line 512 of MobileAnalyticsClient.js ](https://github.com/innFactory/react-native-aws-mobile-analytics/blob/master/src/MobileAnalyticsClient.js#L521)

It looks like @rahuljaguste added a patch with these two commits 
- https://github.com/rahuljaguste/react-native-aws-mobile-analytics/commit/d3a50f212ce42ff9a689a444f6bc226cd48fad4b
- https://github.com/rahuljaguste/react-native-aws-mobile-analytics/commit/16c51c274795a93c9300426f73bdf2cfd31cce6b

Can you confirm that would fix the issue and if so would it be possible to merge this into the master branch?

Thanks!

**Comment by spoeck** [comment]
Hey thanks for the issue and your very detailed description :)
This is an error I made while transforming the [origin file](https://github.com/aws/aws-sdk-mobile-analytics-js/blob/master/lib/MobileAnalyticsClient.js) to a react-native compatible one. Client is the reference to it self but the exception array wasn't defined either. I will correct that and publish a new version.

Using the workaround of @rahuljaguste could work, but I really recommend to use the aws-sdk for react-native for AsyncStore support and so on. Also if you are using the aws-sdk for other aws services it could be a bad idea to use the plain javascript version or a mix of it.

**Comment by rahuljaguste** [comment]
hey guys,
My workaround works fine. Already tried and tested. I am using this along with https://github.com/aws/amazon-cognito-identity-js. Once you are successfully authenticated with Cognito, you can call the initialize method
e.g.

cognitoUser.authenticateUser(authenticationDetails, {
 onSuccess: function (result) {
            console.log('access token + ' + result.getAccessToken().getJwtToken());
            //POTENTIAL: Region needs to be set if not already set previously elsewhere.
            AWS.config.region = '<region>';
            AWS.config.credentials = new AWS.CognitoIdentityCredentials({
                IdentityPoolId : '...', // your identity pool id here
                Logins : {
                    // Change the key below according to the specific region your user pool is in.
                    'cognito-idp.<region>.amazonaws.com/<YOUR_USER_POOL_ID>' : result.getIdToken().getJwtToken()
                }
            });
            // Instantiate aws sdk service objects now that the credentials have been updated.
            // example: var s3 = new AWS.S3();
             MobileAnalyticsClient.initialize(() => {
        MobileAnalyticsClient.recordEvent('Init', {'attribute_1': 'test1', 'attribute_2': 'test2'}, {'metric_1': 1});
      });
        },
        onFailure: function(err) {
            alert(err);
        },
    });

Also make sure hook up the below policy to your userpool
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "mobileanalytics:PutEvents",
            "Resource": "*"
        }
    ]
}`
I hope this helps. Feel free to drop me a message if you need any more assistance.

**Comment by spoeck** [comment]
@rahuljaguste thanks for your reply!

My new version v0.1.2 works without your workaround. Though, I'm sure your workaround is fine, I think it's better to use the aws-sdk for react-native (`aws-sdk/dist/aws-sdk-react-native`). Actually I don't know all the differences but I heard of some S3 issues if you use the normal aws-sdk-js with RN. And I had really bad side effects when I mixed the normal aws-sdk-js with the aws-sdk-react-native.

**Comment by rahuljaguste** [comment]
@spoeck you are welcome. As long as it works for you its all fine. I have moved all my code to aws-sdk(import AWS from 'aws-sdk') and it seems to be working good. Even S3 uploads are working for me without any issue. I can share my S3 upload code if you need. Do let me know.
